-Tabela musi byæ nowa bo inaczej bêd¹ dziwne nr index-

INSERT INTO CATEGORIES(TAG,NAME) VALUES ('XXX','Wybierz Kategoriê');

INSERT INTO CATEGORIES(TAG,NAME) VALUES ('AWN','Aran¿acja Wnêtrz');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('HYD','Hydrualika');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('ELE','Elektryka');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('GAZ','Gazownictwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('MAL','Malarstwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('KOM','Kominiarstwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('STO','Stolarstwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('DIN','Dom Inne');

INSERT INTO CATEGORIES(TAG,NAME) VALUES ('AOG','Aran¿acja Ogrodów');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('OGR','Ogrodnictwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('BRU','Brukarstwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('OGD','Ogrodzenia');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('KAM','Kamieniarstwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('GIN','Ogród Inne');

INSERT INTO CATEGORIES(TAG,NAME) VALUES ('MEC','Mechanik');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('BLA','Blacharz');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('LAK','Lakiernik');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('DET','Detaling');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('WUL','Wulkanizacja');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('MIN','Motoryzacja Inne');

INSERT INTO CATEGORIES(TAG,NAME) VALUES ('KOR','Korepetycje');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('INF','Informatyka');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('URO','Uroda');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('NAP','Naprawa i Serwis');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('TRA','Transport');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('MON','Monter');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('UIN','Us³ugi Inne');