INSERT INTO CATEGORIES(TAG,NAME) VALUES ('XXX','Wybierz Kategoriê');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('REM','Prace remontowe');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('REM','Prace wykoñczeniowe');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('OGR','Ogród');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('STO','Stolarstwo');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('ELE','Elektryka');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('CAT','Catering');
INSERT INTO CATEGORIES(TAG,NAME) VALUES ('CUK','Cukiernictwo');