//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajsterFinale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public Advertisement()
        {
            this.Date = DateTime.Now;
        }
        public int ID { get; set; }
        public string Customer { get; set; }
        public string Specialist { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Category { get; set; }
        public string Place { get; set; }
        public string Picture { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
