//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajsterFinale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAV
    {
        public int ID { get; set; }
        public int USER { get; set; }
        public int ADV { get; set; }
    
        public virtual ADVERTS ADVERTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
