//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajsterFinale.Models
{
    using System;
    using System.Collections.Generic;

    public partial class IMAGES_MESSAGE
    {
        public int IMAGE_ID { get; set; }
        public string IMAGE_TITLE { get; set; }
        public string IMAGE_PATH { get; set; }
        public int MSG_FROM { get; set; }
        public int MSG_TO { get; set; }
        public int ADVERT_ID { get; set; }
        public int MESSAGE_ID { get; set; }

        public virtual MESSAGE MESSAGE { get; set; }
    }
}
