//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajsterFinale.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MESSAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MESSAGE()
        {
            this.IMAGES_MESSAGE = new HashSet<IMAGES_MESSAGE>();
        }

        public int ID { get; set; }
        public int MSG_FROM { get; set; }
        public int MSG_TO { get; set; }
        public string TEXT { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<bool> IS_READ { get; set; }
        public int ADVERT_ID { get; set; }

        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
        public virtual ADVERTS ADVERTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGES_MESSAGE> IMAGES_MESSAGE { get; set; }
    }
}
