
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MajsterFinale.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Permission
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Permission()
    {

        this.Old_Pass = new HashSet<Old_Pass>();

    }


    public string Login { get; set; }

    public Nullable<bool> Admin { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Old_Pass> Old_Pass { get; set; }

    public virtual User User { get; set; }

}

}
