//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajsterFinale.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.ADVERTS = new HashSet<ADVERTS>();
            this.FAV = new HashSet<FAV>();
            this.MESSAGE = new HashSet<MESSAGE>();
            this.MESSAGE1 = new HashSet<MESSAGE>();
        }

        public int USER_ID { get; set; }
        [DisplayName("Login")]
        [Required(ErrorMessage = "Pole jest wymagane")]
        public string LOGIN { get; set; }

        [DisplayName("Has³o")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }

        [DisplayName("Powtórz Has³o")]
        [DataType(DataType.Password)]
        public string REPASSWORD { get; set; }

        [DisplayName("E-mail")]
        [DataType(DataType.EmailAddress)]
        public string MAIL { get; set; }

        [DisplayName("Powtórz E-mail")]
        [DataType(DataType.EmailAddress)]
        public string REMAIL { get; set; }

        [DisplayName("Imiê")]
        [Required(ErrorMessage = "Pole jest wymagane")]
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public Nullable<bool> VERIFIED { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public string PHONE_NUMBER { get; set; }
        public System.Guid ACTIVATIONCODE { get; set; }
        
        [DisplayName("Kod aktywacyjny")]
        public System.Guid REACTIVATIONCODE { get; set; }

        //[MustBeTrue(ErrorMessage = "Nale¿y zaakceptowaæ regulamin oraz zapoznaæ siê z polityk¹ ochrony prywatnoœci")]
        public bool TERMS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVERTS> ADVERTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAV> FAV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE> MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE> MESSAGE1 { get; set; }
    }
    internal class MustBeTrueAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            return value is bool && (bool)value;
        }

    }
}
