//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajsterFinale.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.ADVERTS = new HashSet<ADVERTS>();
            this.FAV = new HashSet<FAV>();
            this.MESSAGE = new HashSet<MESSAGE>();
            this.MESSAGE1 = new HashSet<MESSAGE>();
        }

        public int USER_ID { get; set; }
        [DisplayName("Has≥o")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&.-]).{8,30}$",
        ErrorMessage = "Has≥o nie moøe byÊ krÛtsze niø 8 znakÛw. Musi zawieraÊ dodatkowo przynajmniej 1 cyfre, znak specjalny oraz duøπ literÍ.")]
        [StringLength(30, MinimumLength = 8, ErrorMessage = "Has≥o musi sk≥adaÊ sie z minumum 8 znakÛw")]
        public string REGISTERPASSWORD { get; set; }
        [DisplayName("Has≥o")]
        [DataType(DataType.Password)]
        [StringLength(30, MinimumLength = 8, ErrorMessage = "Has≥o musi sk≥adaÊ sie z minumum 8 znakÛw")]
        public string PASSWORD { get; set; }
        [DisplayName("PowtÛrz Has≥o")]
        [DataType(DataType.Password)]
        [StringLength(30, MinimumLength = 8, ErrorMessage = "Has≥o musi sk≥adaÊ sie z minumum 8 znakÛw")]
        public string REPASSWORD { get; set; }
        [DisplayName("E-mail")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "ProszÍ podaÊ prawid≥owy mail")]
        public string MAIL { get; set; }
        [DisplayName("ImiÍ")]
        [Required(ErrorMessage = "Pole jest wymagane")]
        [RegularExpression(@"[A-Za-zøüÊÒÛ≥ÍπúØè∆•å £”—]+", ErrorMessage = "ProszÍ podaÊ prawid≥owe imie")]
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Poprawne imiÍ ma miÍdzy 3 a 15 znakÛw")]
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public Nullable<bool> VERIFIED { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        [Display(Name = "Numer Telefonu")]
        [DataType(DataType.PhoneNumber)]
        [MinLength(9)]
        [MaxLength(9)]
        [RegularExpression(@"^\(?([1-9]{1})\)?([0-9]{8})$", ErrorMessage = "Nieprawid≥owy numer telefonu. Poprawny format: 123456789")]
        public string PHONE_NUMBER { get; set; }
        public string RESETPASSWORDCODE { get; set; }
        public System.DateTime REGISTER_DATE { get; set; }
        public bool TERMS { get; set; }
        public bool rememberMe { get; set; }
        public Nullable<System.DateTime> LASTRESETPASSDATE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVERTS> ADVERTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAV> FAV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE> MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE> MESSAGE1 { get; set; }
    }
}
